export const languages = [
  {'lang': 'Africâner', 'cod':'af'},
  {'lang': 'Albanês', 'cod':'sq'},
  {'lang': 'Amárico', 'cod':'am'},
  {'lang': 'Árabe', 'cod':'ar'},
  {'lang': 'Armênio', 'cod':'hy'},
  {'lang': 'Azerbaijano', 'cod':'az'},
  {'lang': 'Basco', 'cod':'eu'},
  {'lang': 'Bielorrusso', 'cod':'be'},
  {'lang': 'Bengali', 'cod':'bn'},
  {'lang': 'Bósnio', 'cod':'bs'},
  {'lang': 'Búlgaro', 'cod':'bg'},
  {'lang': 'Catalão', 'cod':'ca'},
  {'lang': 'Cebuano', 'cod':'ceb'},
  {'lang': 'Chinês (simplificado)', 'cod':'z-CN'},
  {'lang': 'Chinês (tradicional)', 'cod':'z-TW'},
  {'lang': 'Córsico', 'cod':'co'},
  {'lang': 'Croata', 'cod':'hr'},
  {'lang': 'Tcheco', 'cod':'cs'},
  {'lang': 'Dinamarquês', 'cod':'da'},
  {'lang': 'Holandês', 'cod':'nl'},
  {'lang': 'Inglês', 'cod':'en'},
  {'lang': 'Esperanto', 'cod':'eo'},
  {'lang': 'Estoniano', 'cod':'et'},
  {'lang': 'Finlandês', 'cod':'fi'},
  {'lang': 'Francês', 'cod':'fr'},
  {'lang': 'Frísio', 'cod':'fy'},
  {'lang': 'Galego', 'cod':'gl'},
  {'lang': 'Georgiano', 'cod':'ka'},
  {'lang': 'Alemão', 'cod':'de'},
  {'lang': 'Grego', 'cod':'el'},
  {'lang': 'Guzerate', 'cod':'gu'},
  {'lang': 'Crioulo haitiano', 'cod':'ht'},
  {'lang': 'Hauçá', 'cod':'ha'},
  {'lang': 'Havaiano	haw (ISO-639', 'cod':'2)'},
  {'lang': 'Hebraico	he ou', 'cod':'iw'},
  {'lang': 'Hindi', 'cod':'hi'},
  {'lang': 'Hmong	hmn (ISO-639', 'cod':'2)'},
  {'lang': 'Húngaro', 'cod':'hu'},
  {'lang': 'Islandês', 'cod':'is'},
  {'lang': 'Igbo', 'cod':'ig'},
  {'lang': 'Indonésio', 'cod':'id'},
  {'lang': 'Irlandês', 'cod':'ga'},
  {'lang': 'Italian', 'cod':'it'},
  {'lang': 'Japonês', 'cod':'ja'},
  {'lang': 'Javanês', 'cod':'jv'},
  {'lang': 'Canará', 'cod':'kn'},
  {'lang': 'Cazaque', 'cod':'kk'},
  {'lang': 'Cmer', 'cod':'km'},
  {'lang': 'Kinyarwanda', 'cod':'rw'},
  {'lang': 'Coreano', 'cod':'ko'},
  {'lang': 'Curdo', 'cod':'ku'},
  {'lang': 'Quirguiz', 'cod':'ky'},
  {'lang': 'Laosiano', 'cod':'lo'},
  {'lang': 'Latim', 'cod':'la'},
  {'lang': 'Letão', 'cod':'lv'},
  {'lang': 'Lituano', 'cod':'lt'},
  {'lang': 'Luxemburguês', 'cod':'lb'},
  {'lang': 'Macedônio', 'cod':'mk'},
  {'lang': 'Malgaxe', 'cod':'mg'},
  {'lang': 'Malaio', 'cod':'ms'},
  {'lang': 'Malaiala', 'cod':'ml'},
  {'lang': 'Maltês', 'cod':'mt'},
  {'lang': 'Maori', 'cod':'mi'},
  {'lang': 'Marata', 'cod':'mr'},
  {'lang': 'Mongol', 'cod':'mn'},
  {'lang': 'Myanmar (birmanês)', 'cod':'my'},
  {'lang': 'Nepalês', 'cod':'ne'},
  {'lang': 'Norueguês', 'cod':'no'},
  {'lang': 'Nianja (Chichewa)', 'cod':'ny'},
  {'lang': 'Oriá', 'cod':'or'},
  {'lang': 'Pashto', 'cod':'ps'},
  {'lang': 'Persa', 'cod':'fa'},
  {'lang': 'Polonês', 'cod':'pl'},
  {'lang': 'Português (Portugal, Brasil)', 'cod':'pt'},
  {'lang': 'Punjabi', 'cod':'pa'},
  {'lang': 'Romeno', 'cod':'ro'},
  {'lang': 'Russo', 'cod':'ru'},
  {'lang': 'Samoano', 'cod':'sm'},
  {'lang': 'Gaélico escocês', 'cod':'gd'},
  {'lang': 'Sérvio', 'cod':'sr'},
  {'lang': 'Sesoto', 'cod':'st'},
  {'lang': 'Xona', 'cod':'sn'},
  {'lang': 'Sindi', 'cod':'sd'},
  {'lang': 'Sinhala (cingalês)', 'cod':'si'},
  {'lang': 'Eslovaco', 'cod':'sk'},
  {'lang': 'Esloveno', 'cod':'sl'},
  {'lang': 'Somali', 'cod':'so'},
  {'lang': 'Espanhol', 'cod':'es'},
  {'lang': 'Sundanês', 'cod':'su'},
  {'lang': 'Suaíli', 'cod':'sw'},
  {'lang': 'Sueco', 'cod':'sv'},
  {'lang': 'Tagalo (filipino)', 'cod':'tl'},
  {'lang': 'Tajique', 'cod':'tg'},
  {'lang': 'Tâmil', 'cod':'ta'},
  {'lang': 'Tártaro', 'cod':'tt'},
  {'lang': 'Telugu', 'cod':'te'},
  {'lang': 'Tailandês', 'cod':'th'},
  {'lang': 'Turco', 'cod':'tr'},
  {'lang': 'Turcomano', 'cod':'tk'},
  {'lang': 'Ucraniano', 'cod':'uk'},
  {'lang': 'Urdu', 'cod':'ur'},
  {'lang': 'Uyghur', 'cod':'ug'},
  {'lang': 'Usbeque', 'cod':'uz'},
  {'lang': 'Vietnamita', 'cod':'vi'},
  {'lang': 'Galês', 'cod':'cy'},
  {'lang': 'Xosa', 'cod':'xh'},
  {'lang': 'Ídiche', 'cod':'yi'},
  {'lang': 'Iorubá', 'cod':'yo'},
  {'lang': 'Zulu', 'cod':'zu'},
];